# Generated by Django 4.2.7 on 2023-12-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='author',
            name='phone_num',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
