# Generated by Django 4.2.7 on 2023-12-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_bio_author_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bio',
            new_name='Bio',
        ),
    ]
