# Generated by Django 4.2.7 on 2023-12-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_rename_bio_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Bio',
            field=models.TextField(default='this is bio'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone_num',
            field=models.CharField(default='012', max_length=12),
        ),
    ]
